In [2]:
import pandas as pd
names = ['Bob','Jessica','Mary','John','Mel']
grades = [76,95,77,78,99]
bsdegrees = [1,1,0,0,1]
msdegrees = [2,1,0,0,0]
phddegrees = [0,1,0,0,0]
EducationList = zip(names,grades,bsdegrees,msdegrees,phddegrees)
df = pd.DataFrame(data=EducationList,
                 columns=['Names','Grades','BS Degrees','MS Degrees','PhD Degrees'])
df

     Names  Grades  BS Degrees  MS Degrees  PhD Degrees
0      Bob      76           1           2            0
1  Jessica      95           1           1            1
2     Mary      77           0           0            0
3     John      78           0           0            0
4      Mel      99           1           0            0

In [3]:
#Summary Statistics of Grades
gradeCount = df['Grades'].count() # number of values
print("The number of grades in the dataset is:", gradeCount)

gradeMean = df['Grades'].mean() # arithmetic average
print("The average grade is:", gradeMean)

gradeMedian = df['Grades'].median() #median
print("The median grade is:", gradeMedian)

gradeMode = df['Grades'].mode() #mode
print("The mode for grades is:")
print(gradeMode)

gradeVariance = df['Grades'].var() #variance
print("The variance for grades is:", gradeVariance)

gradeStd = df['Grades'].std() # standard deviation
print("The standard deviation for grades is:", gradeStd)

gradeMin = df['Grades'].min() # minimum
print("The minimum grade is:", gradeMin)

gradeMax = df['Grades'].max() # maximum
print("The maximum grade is:", gradeMax)

gradeFirstQuantile = df['Grades'].quantile(.25) # first quartile
print("The first quantile (.25) for grades is:", gradeFirstQuantile)

gradeSecondQuantile = df['Grades'].quantile(.5) # second quartile
print("The second quantile (.50) for grades is:", gradeSecondQuantile)

gradeThirdQuantile = df['Grades'].quantile(.75) # third quartile
print("The third quantile (.75) for grades is:", gradeThirdQuantile)

The number of grades in the dataset is: 5
The average grade is: 85.0
The median grade is: 78.0
The mode for grades is:
0    76
1    77
2    78
3    95
4    99
dtype: int64
The variance for grades is: 122.5
The standard deviation for grades is: 11.067971810589327
The minimum grade is: 76
The maximum grade is: 99
The first quantile (.25) for grades is: 77.0
The second quantile (.50) for grades is: 78.0
The third quantile (.75) for grades is: 95.0

In [25]:
#Summary Statistics of BS Degrees
bsDegreesCount = df['BS Degrees'].count() # number of values
print("The number of BS degrees in the dataset is:", bsDegreesCount)

bsDegreesMean = df['BS Degrees'].mean() # arithmetic average
print("The average number of BS degrees is:", bsDegreesMean)

bsDegreesMedian = df['BS Degrees'].median() #median
print("The median for BS degrees is:", bsDegreesMedian)

bsDegreesMode = df['BS Degrees'].mode() #mode
print("The mode for BS degrees is:")
print(bsDegreesMode)

bsDegreesVariance = df['BS Degrees'].var() #variance
print("The variance for BS degrees is:", bsDegreesVariance)

bsDegreesStd = df['BS Degrees'].std() # standard deviation
print("The standard deviation for BS degrees is:", bsDegreesStd)

bsDegreesMin = df['BS Degrees'].min() # minimum
print("The minimum for BS degrees is:", bsDegreesMin)

bsDegreesMax = df['BS Degrees'].max() # maximum
print("The maximum for BS degrees is:", bsDegreesMax)

bsDegreesFirstQuantile = df['BS Degrees'].quantile(.25) # first quartile
print("The first quantile (.25) for BS degrees is:", bsDegreesFirstQuantile)

bsDegreesSecondQuantile = df['BS Degrees'].quantile(.50) # second quartile
print("The second quantile (.50) for BS degrees is:", bsDegreesSecondQuantile)

bsDegreesThirdQuantile = df['BS Degrees'].quantile(.75) # third quartile
print("The third quantile (.75) for BS degrees is:", bsDegreesThirdQuantile)

The number of BS degrees in the dataset is: 5
The average BS degrees is: 0.6
The median BS degrees is 1.0
The mode for BS degrees is:
0    1
dtype: int64
The variance for BS degrees is: 0.30000000000000004
The standard deviation for BS degrees is: 0.5477225575051662
The minimum for BS degrees is: 0
The maximum for BS degrees is: 1
The first quantile (.25) for BS degrees is: 0.0
The second quantile (.50) for BS degrees is: 1.0
The third quantile (.75) for BS degrees is: 1.0

In [4]:
#Summary Statistics of MS Degrees
msDegreesCount = df['MS Degrees'].count() # number of values
print("The number of MS degrees in the dataset is:", msDegreesCount)

msDegreesMean = df['MS Degrees'].mean() # arithmetic average
print("The average number of MS degrees is:", msDegreesMean)

msDegreesMedian = df['MS Degrees'].median() #median
print("The median for MS degrees is:", msDegreesMedian)

msDegreesMode = df['MS Degrees'].mode() #mode
print("The mode for MS degrees is:")
print(msDegreesMode)

msDegreesVariance = df['MS Degrees'].var() #variance
print("The variance for MS degrees is:", msDegreesVariance)

msDegreesStd = df['MS Degrees'].std() # standard deviation
print("The standard deviation for MS degrees is:", msDegreesStd)

msDegreesMin = df['MS Degrees'].min() # minimum
print("The minimum for MS degrees is:", msDegreesMin)

msDegreesMax = df['MS Degrees'].max() # maximum
print("The maximum for MS degrees is:", msDegreesMax)

msDegreesFirstQuantile = df['MS Degrees'].quantile(.25) # first quartile
print("The first quantile (.25) for MS degrees is:", msDegreesFirstQuantile)

msDegreesSecondQuantile = df['MS Degrees'].quantile(.50) # second quartile
print("The second quantile (.50) for MS degrees is:", msDegreesSecondQuantile)

bsDegreesThirdQuantile = df['BS Degrees'].quantile(.75) # third quartile
print("The third quantile (.75) for BS degrees is:", bsDegreesThirdQuantile)

The number of MS degrees in the dataset is: 5
The average number of MS degrees is: 0.6
The median for MS degrees is: 0.0
The mode for MS degrees is:
0    0
dtype: int64
The variance for MS degrees is: 0.7999999999999998
The standard deviation for MS degrees is: 0.8944271909999157
The minimum for MS degrees is: 0
The maximum for MS degrees is: 2
The first quantile (.25) for MS degrees is: 0.0
The second quantile (.50) for MS degrees is: 0.0
The third quantile (.75) for BS degrees is: 1.0

In [5]:
#Summary Statistics of PhD Degrees Using Describe()
print(df['PhD Degrees'].describe()) #describe
print("median\t", df['PhD Degrees'].median()) #median
print("var\t", df['PhD Degrees'].var()) #variance

count    5.000000
mean     0.200000
std      0.447214
min      0.000000
25%      0.000000
50%      0.000000
75%      0.000000
max      1.000000
Name: PhD Degrees, dtype: float64
median	 0.0
var	 0.20000000000000007